server:
 port: 8089
    
    
    
spring:
  cloud:
    gateway:
      routes:
         - id: registerAndLogin_sportsManagement-1
           uri: http://localhost:8081
           predicates:
             - Path=/entrypoint/**
         - id: Students_sportsManagement-2
           uri: http://localhost:8082
           predicates:              -Path=/timetable/**
        